name: Build Windows EXE

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-2022

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install pyinstaller

      - name: Build EXE
        run: |
          pyinstaller --onefile --name Xitrust_LOG_query Xitrust_Log_Query.py

      - name: Upload EXE
        uses: actions/upload-artifact@v4
        with:
          name: windows-exe
          path: dist/Xitrust_LOG_query.exe
